<a href="https://colab.research.google.com/github/PomesHouse/SkillTreePython-DataAnalysis/blob/main/05_NumPy_%EB%B0%B0%EC%97%B4%EC%9D%98%EC%97%B0%EC%82%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CH05 Numpy  - 배열의 연산

---
* 날짜:
* 이름:


In [1]:
import numpy as np

---
### **(1) 산술 연산(Arithmetic Operators)**
---

|연산자|범용함수|설명|
|--|--|--|
|+|`np.add`|덧셈|
|-|`np.substract`|뺄셈|
|-|`np.negative`|단항음수|
|*|`np.multiply`|곱셈|
|/|`np.divide`|나눗셈|
|//|`np.floor_divide`|나눗셈 내림|
|**|`np.power`|지수 연산|
|%|`np.mod`|나머지 연산|

파이썬의 수치자료형에서 사용하는 모든 연산을 넘파이 배열에서 사용할 수 있습니다. 

리스트에서는 불가능했던 배열간의 덧셈도 아래와 같이 사용 가능합니다.

```
a = np.array([1,2,3])
b = np.array([-1,2,-3])
a*b
```



In [7]:
a = np.array([1,2,3])
b = np.array([-1,2,-3])
a*b

array([-1,  4, -9])


#### **|  브로드캐스팅 (Broadcasting)**

NumPy의 배열 연산은 벡터화(vectorized) 연산을 사용합니다. 브로드 캐스팅은 배열 각 요소에 대한 반복적인 계산을 효율적으로 수행합니다.


<p align='center'>
<img src=https://github.com/yebiny/SkillTreePython-DataAnalysis/blob/main/imgs/ch0105-01.png?raw=true width=560>
</p>

In [3]:
a = np.arange(1,10).reshape(3,3)
print(a * 2)
print(a * [2,2,2])

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


---
### **(2) 수학 관련 함수**
---





#### **| 절대값 함수 (Absolute Function)**





* `np.absolute(n)` = `np.abs(n)` : `n`의 절대값 반환

```
print(b)
np.abs(b)
```


In [ ]:
print(b)
print(np.abs(b))

[-1  2 -3]
[1 2 3]


#### **| 제곱/제곱근 함수**

* `np.square(n)`: `n`의 제곱을 반환
* `np.sqrt(n)` : `n`의 제곱근을 반환

```
n = 25
print(np.square(n), np.sqrt(n))
```

In [ ]:
# 제곱근: 어떤 수 x를 제곱하여 a가 되었을 때의 x값
n = 25
print(np.square(n), np.sqrt(n))

625 5.0


#### **| 지수/로그 함수**

* `np.exp(n)` : 자연상수 `e`(=~2.71..)의 `n` 제곱을 반환
* `np.exp2(n)` : 상수 `2`의 `n` 제곱을 반환


```
[np.exp2(n) for n in range(10)]
```







In [ ]:
print([np.exp(n) for n in range(10)])
print([np.exp2(n) for n in range(10)])

[1.0, 2.718281828459045, 7.38905609893065, 20.085536923187668, 54.598150033144236, 148.4131591025766, 403.4287934927351, 1096.6331584284585, 2980.9579870417283, 8103.083927575384]
[1.0, 2.0, 4.0, 8.0, 16.0, 32.0, 64.0, 128.0, 256.0, 512.0]



* `np.log(n)` : 밑이 `e`인 로그값을 반환합니다. 
* `np.log2(n)` : 밑이 `2`인 로그값을 반환합니다.
* `np.log10(n)` : 밑이 `10`인 로그값을 반환합니다.

```
n = [10,100,1000,10000]
np.log10(n)
```

In [ ]:
n = [2,4,8,16]
np.log2(n)

array([1., 2., 3., 4.])

In [ ]:
n = [10,100,1000,10000]
np.log10(n)

array([1., 2., 3., 4.])

#### **| 삼각 함수(Trigonometrical Function)**

|함수|설명|
|--|--|
|`np.sin`|사인|
|`np.cos`|코사인|
|`np.tan`|탄젠트|
|`np.arcsin`|아크 사인|
|`np.argcos`|아크 코사인|
|`np.argtan`|아크 탄젠트|
|`np.sinh`|하이퍼볼릭 사인|
|`np.cosh`|하이퍼볼릭 코사인|
|`np.tanh`|하이퍼볼릭 탄젠트|
|`np.arcsinh`|하이퍼볼릭 아크 사인|
|`np.arccosh`|하이퍼볼릭 아크 코사인|
|`np.arctanh`|하이퍼볼릭 아크 탄젠트|
|`np.deg2rad`|각도를 라디안으로 변환|
|`np.rad2deg`|라디안을 각도로 변환|
|`np.hypot`|유클리드 거리계산|

학창시절 아래 삼각함수 표를 외워본 경험이 있을 겁니다. 더이상 이를 외울 필요는 없습니다. 코드가 알아서 해줄테니까요. 값이 똑같이 나오는지 확인해 봅시다.

<p align='center'>
<img src=https://github.com/yebiny/SkillTreePython-DataAnalysis/blob/main/imgs/ch0105-02.png?raw=true width=500>
</p>

```
n = 0
np.sin(n), np.cos(n), np.tan(n)
```

In [14]:
n = 0
np.sin(n), np.cos(n), np.tan(n)

(0.0, 1.0, 0.0)

#### **| 집계 함수(Aggregate Functions)**

|함수|설명|
|--|--|
|`np.sum()`|배열 내 합을 반환|
|`np.cumsum()`|배열 내 누적합 반환|
|`np.prod()`|배열 내 곱 반환|
|`np.diff()`|배열 내 차 반환|
|`np.min()`|최소값 반환|
|`np.max()`|최대값 반환|
|`np.mean()`|평균 반환|
|`np.std()`|표준편차 반환|
|`np.var()`|분산 반환|
|`np.median()`|중앙값 반환|
|`np.argmin()`|최소값 인덱스 반환|
|`np.argmax()`|최소값 인덱스 반환|


```
print(a)
print('누적합: ',np.cumsum(a))
print('곱: ',np.prod(a))
print('차: ',np.diff(a))
print('중앙값: ',np.median(a))
```

In [16]:
print(a)
print('누적합: ',np.cumsum(a)) # 하나씩 누적된 합이 나온다. 
print('곱: ',np.prod(a))
print('차: ',np.diff(a))
print('중앙값: ',np.median(a))

[1 2 3]
누적합:  [1 3 6]
곱:  6
차:  [1 1]
중앙값:  2.0


머신러닝에서 자주 사용되는 함수는 `np.argmax`입니다. `np.argmax`는 최대값의 인덱스를 반환하는데요, 최대값 자체가 아닌 인덱스가 언제 필요할까요?

예시를 들어 봅시다. `y`에 카드 이름이, `x`에는 각 카드가 뽑힐 확률이 들어 있습니다. 뽑힐 확률이 가장 높은 카드를 아래와 같이 구할 수 있습니다.

```
x = [0.1, 0.2, 0.6, 0.1]
y = ['a', 'b', 'c', 'd']
idx = np.argmax(x)
print(y[idx]) # 팬시 인덱싱
```

In [17]:
x = [0.1, 0.2, 0.6, 0.1]
y = ['a', 'b', 'c', 'd']
idx = np.argmax(x)
print(idx)
print(y[idx]) 

2
c


---
### **(3) 벡터/행렬 연산**
---

|함수|설명|
|--|--|
|`np.matmul()`|=`@`, 행렬곱|
|`np.dot()`|내적|
|`np.prod()`|외적|




* `np.matmul(a1, a2)` : 배열 `a1`과 `a2`의 행렬곱을 수행합니다. 

일반적인 행렬곱을 `matmul`을 통해서 할 수 있습니다. 

```
A = np.array([[1,2],
              [0,1]])
B = np.array([[1,0],
              [0,1]])
print(np.matmul(A,B))
print(A@B)
```


In [18]:
A = np.array([[1,2],
              [0,1]])
B = np.array([[1,0],
              [0,1]])
print(np.matmul(A,B))
print(A@B)

[[1 2]
 [0 1]]
[[1 2]
 [0 1]]


* `np.dot(a1, a2)`: 배열 `a1`과 `a2`의 벡터 내적을 수행합니다.

벡터 내적은 벡터 내 같은 인덱스의 값을 곱하고 모두 더한 것입니다.

```
print(a, b)
print(sum(a*b))
print(np.dot(a,b))
```




In [19]:
print(a, b)
print(sum(a*b))
print(np.dot(a,b))

[1 2 3] [-1  2 -3]
-6
-6


---
### **(4) 비교 연산**
---

비교 연산자를 이용하면 `boolean` 값으로 이루어진 배열을 반환합니다.





#### **| 값 비교**


|연산자|비교 범용 함수|
|--|--|
|`==`|`np.equal`|
|`!=`|`np.not_equal`|
|`<`| `np.less`|
|`<=`|`np.less_equal`|
|`>`| `np.greater`|
|`>=`|`np.greater_equal`|

```
print(a)
print(b)
a==b, a<b, a>b
```

In [20]:
print(a)
print(b)
a==b, a<b, a>b

[1 2 3]
[-1  2 -3]


(array([False,  True, False]),
 array([False, False, False]),
 array([ True, False,  True]))


#### **| 예외값 비교**



|함수|설명|
|--|--|
|`np.isinf`|`inf` 값이면 `True`, 아니면 `False`|
|`np.isfinite`|`inf, nan` 값이면 `False`, 아니면 `True`|
|`np.isnan`|`nan` 값이면 `True`, 아니면 `False`|

```
a = [np.inf, np.nan, 0]
print(np.isinf(a))
print(np.isfinite(a))
print(np.isnan(a))
```

In [21]:
a = [np.inf, np.nan, 0]
print(a)

[inf, nan, 0]


In [31]:
print(np.isinf(a))
print(np.isnan(a))
print(np.isfinite(a))

[False False False False False]
[False False False False False]
[ True  True  True  True  True]


#### **| 논리 연산자**

|함수|설명|
|--|--|
|`np.all()`|모두 `True`일때 `True` 반환|
|`np.any()`|모두 `False`일때 `False` 반환|

파이썬의 논리 연산자와 동일 합니다. 아래와 같이 숫자 자료형을 바로 넣으면 0 일 때는 `False`, 그 외에는 `True`로 인식하여 연산이 진행됩니다.

```
a = [1,0,1,1,0]
np.all(a), np.any(a)
```

In [29]:
a = [1,0,1,1,0]
np.all(a), np.any(a)

(False, True)

---
### **(5) 정렬**
---


|함수|설명|
|--|--|
|`np.sort()`|오름차순 정렬|
|`np.argsort()`|index 정렬|
|`np.partition()`|`k`개의 작은값 반환|


* `np.sort(a, axis=axis)` : 배열 `a`를 오름차순으로 정렬합니다. 

```
np.random.seed(42);a = np.random.randint(0,12,(3,4))
print(a)
print('axis=0: 위에서 아래로 정렬')
print(np.sort(a, axis=0))
print('axis=1: 좌에서 우로 정렬')
print(np.sort(a, axis=1))
```


In [64]:
np.random.seed(42);
a = np.random. randint(0,12,(4,3))
a

array([[ 6,  3, 10],
       [ 7,  4,  6],
       [ 9,  2,  6],
       [10, 10,  7]])

In [65]:
np.sort(a, axis = 0) # axis = 0 기준으로 1,2,3,4번째 이렇게 된다. 

array([[ 6,  2,  6],
       [ 7,  3,  6],
       [ 9,  4,  7],
       [10, 10, 10]])

In [66]:
np.sort(a, axis = 1) # axis = 1 을 기준으로 1,2,3,4.. 이렇게 된다. 

array([[ 3,  6, 10],
       [ 4,  6,  7],
       [ 2,  6,  9],
       [ 7, 10, 10]])

In [ ]:
# 반대로 하고 싶으면 [::-1]도 된다. 

* `np.argsort(a, axis=axis)` : 배열 `a`를 오름차순 정렬하는  인덱스를 반환

위에서 배웠던 `np.argmax`와 마찬가지로 팬시 인덱싱에서 유용하게 사용됩니다. 

아래와 같이 월별(x) 판매수(y)가 주어졌을 때 판매수 순으로 정렬하고자 합니다. 

```
x = np.array(['1월', '2월', '3월'])
y = np.array([500,230,350])
sort_idx = np.argsort(y)
print(sort_idx)
x[sort_idx][::-1] # 팬시 인덱싱
```

In [125]:
x = np.array(['1월', '2월', '3월'])
y = np.array([500,230,350])
sort_idx = np.argsort(y)
print(sort_idx) # [1,2,0] 가장 앞에 있는게 가장 적은 수의 index
x[sort_idx][::-1] # 팬시 인덱싱

[1 2 0]


array(['1월', '3월', '2월'], dtype='<U2')

## 문제풀이
---

**예제 01**

아래 그림에 있는 산술연산을 각각 코드로 구현하세요

<p align='center'>
<img src=https://github.com/yebiny/SkillTreePython-DataAnalysis/blob/main/imgs/ch0105-03.png?raw=true width=400>
</p>


In [44]:
a = np.array([1,2,3])
print(a + 2, np.add(a, 2))
print(a - 2, np.subtract(a, 2))
print(a % 2, np.mod(a, 2))
print(a ** 2, np.power(a, 2))

[3 4 5] [3 4 5]
[-1  0  1] [-1  0  1]
[1 0 1] [1 0 1]
[1 4 9] [1 4 9]


**예제 02**


아래는 `sum`의 용례를 그림으로 표현한 것입니다. 각 경우에 대해 코드로 구현하세요.

<p align='center'>
<img src=https://github.com/yebiny/SkillTreePython-DataAnalysis/blob/main/imgs/ch0105-04.png?raw=true width=460>
</p>


In [40]:
# aa = np.concatenate([a,a], axis = 1) 이거나 append 로는 원래 1차원이였던 array를 2차원으로 이어붙일 수 없다. 
aa = np.stack([a,a], axis = 0)

array([[1, 2, 3],
       [1, 2, 3]])

In [47]:
aa1 = np.sum(aa)
aa2 = np.sum(aa, axis = 0)
aa3 = np.sum(aa, axis = 1)
print(aa1) # 전체가 다 더해진다. 
print(aa2) # axis = 0 축이 하나가된다.  
print(aa3) # axis = 1 축이 하나가된다.  

12
[2 4 6]
[6 6]


**예제 03**

위와 똑같은 방법으로 3가지 경우에 대해 `min()`을 수행하세요

In [58]:
print(np.min(aa1)) # type이 numpy.int64  
print(np.min(aa2)) # type이 numpy.ndarray
print(np.min(aa3))

12
2
6


**예제 04**

위와 똑같은 방법으로 3가지 경우에 대해 `argmax()`을 수행하세요

In [60]:
print(np.argmax(aa1)) # type이 numpy.int64  
print(np.argmax(aa2)) 
print(np.argmax(aa3)) # 가장 빠른 인덱스 return 

0
2
0


**예제 05**

위와 똑같은 방법으로 3가지 경우에 대해 `std()`을 수행하세요

In [61]:
print(np.std(aa1))
print(np.std(aa2))
print(np.std(aa3))

0.0
1.632993161855452
0.0


**예제 06**

아래는 `any`의 용례를 그림으로 표현한 것입니다. 각 경우에 대해 코드로 구현하고, 왜 이런 결과가 나오는지 정리하세요.


<p align='center'>
<img src=https://github.com/yebiny/SkillTreePython-DataAnalysis/blob/main/imgs/ch0105-05.png?raw=true width=580>
</p>


In [69]:
print(aa)
print(np.any(aa > 2)) # 전체 value 중에서 3이 두개가 있다. True  
print(np.any(aa > 2, axis = 0)) # axis = 0 축이 하나가 된다. 결과값의 쉐입 모양이 (1,x), 첫번째 열의 경우 전부 1이기에 False, 다음은 2라서 False, 마지막은 3이라서 True
print(np.any(aa > 2, axis = 1)) # axis = 1 축이 하나가 된다. 결과값의 쉐입 모양이 (x,1), 첫번째, 두번째 행의 경우 둘다 1,2,3 을 포함하고 있기에 True, True.

[[1 2 3]
 [1 2 3]]
True
[False False  True]
[ True  True]


**예제 07**

위와 똑같은 방법으로 3가지 경우에 대해 `all()`을 수행하고, 왜 이런 결과가 나오는지 정리하세요.

In [70]:
print(aa)
print(np.all(aa > 2)) # 모든 값이 2 초과가 아니기에 False
print(np.all(aa > 2, axis = 0)) # 결과값의 쉐입 모양이 (1,x) 된다고 했을 때 False, False, True가 된다. ([1,2,3]이 되기에)
print(np.all(aa > 2, axis = 1)) # 결과값의 쉐입 모양이 (x,1) 된다고 했을 때, 각 행이 1,2,3 을 모두 포함하고 있기에 False, False가 된다. 

[[1 2 3]
 [1 2 3]]
False
[False False  True]
[False False]


**예제 08**


1에서 100까지의 랜덤값을 가지고 형태가 `(40)` 인 1차원 배열을 `a08`로 바인딩하세요

In [72]:
a08 = np.random.randint(1,101, (40,))
a08

array([100,  24,   3,  22,  53,   2,  88,  30,  38,   2,  64,  60,  21,
        33,  76,  58,  22,  89,  49,  91,  59,  42,  92,  60,  80,  15,
        62,  62,  47,  62,  51,  55,  64,   3,  51,   7,  21,  73,  39,
        18])

**예제 09**

`a08`에서 50보다 큰 수만 가지는 배열을 불리언 연산자를 이용해서 생성하세요.

In [73]:
a08[a08 > 50]

array([100,  53,  88,  64,  60,  76,  58,  89,  91,  59,  92,  60,  80,
        62,  62,  62,  51,  55,  64,  51,  73])

**예제 10**

`a08`에서 50 이하이며 3의 배수만 가지는 배열을 불리언 연산자를 이용해 생성하세요

In [83]:
mask1 = 50 >= a08
mask2 = a08%3 ==0
print(mask1)
print(mask2)
mask = mask1 & mask2 # (and는 안된다)
a08[mask]


[False  True  True  True False  True False  True  True  True False False
  True  True False False  True False  True False False  True False False
 False  True False False  True False False False False  True False  True
  True False  True  True]
[False  True  True False False False False  True False False False  True
  True  True False False False False False False False  True False  True
 False  True False False False False  True False False  True  True False
  True False  True  True]


array([24,  3, 30, 21, 33, 42, 15,  3, 21, 39, 18])

**예제 11**

`a08`에서 90이상이거나 10이하인 수만 가지는 배열을 불리언 연산자를 이용해 생성하세요

In [87]:
mask1 = a08 >= 90
mask2 = a08 <=10
mask = mask1 | mask2
print(a08[mask])

[100   3   2   2  91  92   3   7]


**예제 12**


`a08`을 shape가 `(8,5)`인 2차원 배열로 변환하고 `a12`로 바인딩 하세요.

In [89]:
a12 = a08.reshape(8,5)
a12

array([[100,  24,   3,  22,  53],
       [  2,  88,  30,  38,   2],
       [ 64,  60,  21,  33,  76],
       [ 58,  22,  89,  49,  91],
       [ 59,  42,  92,  60,  80],
       [ 15,  62,  62,  47,  62],
       [ 51,  55,  64,   3,  51],
       [  7,  21,  73,  39,  18]])

**예제 13**


`a12`를 복사하여 `a13`으로 바인딩하고 이를 각 행 별로 정렬하세요

In [91]:
a13 = a12.copy()
print(a12)
print(a13)
np.sort(a13,  axis = 1 )

[[100  24   3  22  53]
 [  2  88  30  38   2]
 [ 64  60  21  33  76]
 [ 58  22  89  49  91]
 [ 59  42  92  60  80]
 [ 15  62  62  47  62]
 [ 51  55  64   3  51]
 [  7  21  73  39  18]]
[[100  24   3  22  53]
 [  2  88  30  38   2]
 [ 64  60  21  33  76]
 [ 58  22  89  49  91]
 [ 59  42  92  60  80]
 [ 15  62  62  47  62]
 [ 51  55  64   3  51]
 [  7  21  73  39  18]]


array([[  3,  22,  24,  53, 100],
       [  2,   2,  30,  38,  88],
       [ 21,  33,  60,  64,  76],
       [ 22,  49,  58,  89,  91],
       [ 42,  59,  60,  80,  92],
       [ 15,  47,  62,  62,  62],
       [  3,  51,  51,  55,  64],
       [  7,  18,  21,  39,  73]])

**예제 14**


`a12`를 복사하여 `a14`로 바인딩하고 각 열 별로 가장 작은수 3개를 찾으세요

In [124]:
a14 = a12.copy()

print(np.sort(a14, axis = 0)[:3])


[[ 2 21  3  3  2]
 [ 7 22 21 22 18]
 [15 24 30 33 51]]


In [ ]:
np.partition()

$A$, $B$, $C$를 아래와 같이 정의하세요.

\begin{align*}
 A&= 
\begin{pmatrix}
1 &2  &1 \\ 
2 &1 & 1\\ 
-1 & 0 & 1
\end{pmatrix}
\end{align*}

\begin{align*}
 B&= 
\begin{pmatrix}
1 &0 \\ 
0 &1 \\ 
1 & 0 
\end{pmatrix}
\end{align*}

\begin{align*}
 C&= 
\begin{pmatrix}
1 \\ 
0  \\ 
-1  
\end{pmatrix}
\end{align*}



In [100]:
A = np.array([[1,2,1],[2,1,1],[-1,0,1]])
B = np.array([[1,0],[0,1],[1,0]])
C = np.array([[1],[0],[-1]])
print(A)
print(B)
print(C)

[[ 1  2  1]
 [ 2  1  1]
 [-1  0  1]]
[[1 0]
 [0 1]
 [1 0]]
[[ 1]
 [ 0]
 [-1]]


**예제 15**


$A$, $B$ 의 행렬곱

In [101]:
A@B

array([[2, 2],
       [3, 1],
       [0, 0]])

**예제 16**


$A$, $C$ 의 행렬곱

In [102]:
A@C

array([[ 0],
       [ 1],
       [-2]])

**예제 17**


$A * C$

In [103]:
 A * C

array([[ 1,  2,  1],
       [ 0,  0,  0],
       [ 1,  0, -1]])

**예제 18**


$B$와 $B^T$의 내적

In [105]:
print(B)
print(B.T)

[[1 0]
 [0 1]
 [1 0]]
[[1 0 1]
 [0 1 0]]


In [104]:
np.dot(B, B.T)

array([[1, 0, 1],
       [0, 1, 0],
       [1, 0, 1]])


20명의 학생의 번호와, 키와, 수행평가 점수가 아래와 같이 정의 되어 있습니다. 

```
idx = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
tall = [178, 171, 179, 173, 152, 157, 175, 180, 182, 165, 160, 164, 174, 163, 158, 159, 172, 155, 177, 162]
score = [57, 64, 85, 30, 58, 72, 84, 63, 49, 94, 70, 54, 60, 68, 74, 78, 92, 86, 51, 37]
```


In [134]:
idx = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
tall = np.array([178, 171, 179, 173, 152, 157, 175, 180, 182, 165, 160, 164, 174, 163, 158, 159, 172, 155, 177, 162])
score = np.array([57, 64, 85, 30, 58, 72, 84, 63, 49, 94, 70, 54, 60, 68, 74, 78, 92, 86, 51, 37])

**예제 19**

키가 큰 순으로 학생들의 번호(idx)를 정렬하세요.



In [139]:
order_tall = np.argsort(tall)
print(order_tall)
print(idx[order_tall][::-1])

[ 4 17  5 14 15 10 19 13 11  9  1 16  3 12  6 18  0  2  7  8]
[ 9  8  3  1 19  7 13  4 17  2 10 12 14 20 11 16 15  6 18  5]


**예제 20**

수행평가 점수가 낮은 순으로 학생들의 번호(idx)를 정렬하세요.


In [137]:
order_score = np.argsort(score)
print(order_score)
print(idx[order_score])

[ 3 19  8 18 11  0  4 12  7  1 13 10  5 14 15  6  2 17 16  9]
[ 4 20  9 19 12  1  5 13  8  2 14 11  6 15 16  7  3 18 17 10]
