<a href="https://colab.research.google.com/github/PomesHouse/SkillTreePython-DataAnalysis/blob/main/01.%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B6%84%EC%84%9D%EA%B8%B0%EC%B4%88/02_NumPy_%EB%B0%B0%EC%97%B4%EC%9D%98%EC%83%9D%EC%84%B1%EA%B3%BC%EC%A0%80%EC%9E%A5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CH02. Numpy  - 배열의 생성과 저장

---
* 날짜:
* 이름:


## 개념정리

`Numpy`(Numerical Python)는 포괄적인 함수, 난수생성, 선형대수학 등 고성능 수학 및 과학 계산에 효울적인 파이썬 라이브러리 입니다. 계산의 편리를 위한 배열(array)를 제공하며 이 배열은 파이썬의 list와 비슷하지만 다차원 데이터를 처리할 수 있고 더 효과적인 다차원 연산이 가능합니다. `Numpy`는 데이터과학의 핵심이라 할 수 있습니다.


> [NumPy Hompage](https://numpy.org/)



```
import numpy as np
```


In [ ]:
import numpy as np

---
### **(1) 리스트와 배열**
---

넘파이의 배열은 파이썬 리스트와 잘 호환 됩니다. 리스트를 생성해 봅시다. 

```
l = [1,2,3,4,5]
```


In [ ]:
l = [1,2,3,4,5]

In [ ]:
l = [[1,2],[3,4]] #list를 사용했을 때 얻을 수 있는 정보는 len밖에 없기에 numpy 배열을 사용한다. 

* `np.array(l)` : 리스트 `l`을 넘파이 배열로 변환합니다. 

이제 이 리스트를 넘파이 배열로 변환해 봅시다. 

```
a = np.array(l)
```

In [ ]:
a = np.array(l)
print(a)

[1 2 3 4 5]


데이터 분석에서 중요한 것은 데이터의 형태 `shape` 입니다. 항상 데이터의 `shape`를 중간중간 확인하는 것을 잊지 마세요. 넘파이 배열에서는 형태를 `.shape`를 써서 확인합니다. 

* `.shape` : 넘파이 배열의 형태 (shape)를 반환합니다.

```
a.shape
```

In [ ]:
a, a.shape

(array([1, 2, 3, 4, 5]), (5,))

#### **| 연습문제**




**연습 01**

아래 그림과 같은 1차원 배열을 생성하고 `shape`를 확인해 보세요.

<p align='center'>
<img src=https://github.com/yebiny/SkillTreePython-DataAnalysis/blob/main/imgs/ch0102-01.png?raw=trueA width=240>
</p>

In [ ]:
a1 = [1,4,1,0,1,2]
a1 = np.array(a1)
a1, a1.shape

(array([1, 4, 1, 0, 1, 2]), (6,))

**연습 02**

아래 그림과 같은 2차원 배열을 생성하고 `shape`를 확인해 보세요. `shape`는 `(5,2)` 가 되게 하세요.

<p align='center'>
<img src=https://github.com/yebiny/SkillTreePython-DataAnalysis/blob/main/imgs/ch0102-02.png?raw=trueA width=80>
</p>

In [ ]:
a2 = np.array([[1,4],[1,0],[1,3],[2,2],[0,2]])
a2, a2.shape


(array([[1, 4],
        [1, 0],
        [1, 3],
        [2, 2],
        [0, 2]]), (5, 2))

**연습 03**

아래 그림과 같은 2차원 배열을 생성하고 `shape`를 확인해 보세요. `shape`는 `(2,3)` 가 되게 하세요.

<p align='center'>
<img src=https://github.com/yebiny/SkillTreePython-DataAnalysis/blob/main/imgs/ch0102-03.png?raw=trueA width=120>
</p>

In [ ]:
a2 = np.array([[1,4,1],[1,0,0]])
a2, a2.shape

(array([[1, 4, 1],
        [1, 0, 0]]), (2, 3))

**연습 04**

위에서 만든 배열을 겹쳐서 3차원으로 확장해 보았습니다. 아래 그림과 같은 3차원 배열을 생성하고 `shape`를 확인해 보세요.

<p align='center'>
<img src=https://github.com/yebiny/SkillTreePython-DataAnalysis/blob/main/imgs/ch0102-04.png?raw=trueA width=120>
</p>

In [ ]:
#(2,2,3) 앞에 2는 2차원이 두개이다.  앞으로 데이터의 갯수가 (가장앞에 있는 것) 될 것.
a3 =np.array([ 
     [[1,4,1],[1,0,0]],
     [[1,4,1],[1,0,0]],
    ])
a3, a3.shape

(array([[[1, 4, 1],
         [1, 0, 0]],
 
        [[1, 4, 1],
         [1, 0, 0]]]), (2, 2, 3))

---
### **(2) 기본 배열 생성**
---


* `np.empty(shape)` : `shape` 형태를 가진 빈 배열을 생성합니다. 


넘파이에서 배열을 생성하기 위해서는 기본적으로 생성할 배열에 대한 형태(shape)를 알고, 이를 기입해야 합니다. 

우선 위에서 만들었던 리스트와 같이 길이 5의 빈 배열을 만들어 봅시다. 


이렇게 생성된 배열에는 예상하지 못한 임의의 값이 들어있습니다. 

```
a = np.empty(5)
print(a)
```


In [ ]:
a = np.empty((3,5))
print(a)

[[4.64142954e-310 1.06099790e-312 1.01855798e-312 9.54898106e-313
  1.03977794e-312]
 [1.01855798e-312 1.23075756e-312 1.08221785e-312 1.01855798e-312
  9.76118064e-313]
 [1.18831764e-312 1.08221785e-312 1.16709769e-312 5.28758761e+180
  1.23637330e+243]]


#### **| 초기값 정하기**

특정 형태의 배열을 만들고 초기값을 바로 세팅하고 싶다면 다음 함수를 사용합니다. 

* `np.zeros(shape)` : `shape` 형태를 가지고 모든 값이 `0`인 배열을 생성합니다. 
* `np.ones(shape)` : `shape` 형태를 가지고 모든 값이 `1`인 배열을 생성합니다.
* `np.full(shape, n)` : `shape` 형태를 가지고 모든 값이 `n`인 배열을 생성합니다.
* `np.eye(n)` : `n x n` 의 단위행렬(identity matrix)를 생성합니다. 


단위행렬이란 주대각선의 원소가 모두 1이고 나머지 원소는 모두 0인 정사각 행렬입니다. 

`np.eye`를 이용해 `3x3` 단위행렬을 만들고 어떻게 생겼는지 확인해 봅시다. 

```
np.eye(3)
```





In [ ]:
#요약 n차 정사각행렬에서 주대각선(主對角線)의 원소가 모두 1이고, 다른 원소는 모두 0인 행렬이다. 
#단위행렬 E를 임의의 행렬 A와 곱하면 행렬 A가 얻어진다.
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

길이가 `10`이고 모든 값이 `2` 로 이루어진 배열을 생성해 봅시다. 

```
np.full(10, 2)

```

In [ ]:
np.full((5,5),5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

#### **| 값 범위 정하기**

파이썬의 `range`와 마찬가지로 넘파이에도 값의 범위를 정해주는 함수들이 있습니다. 

* `np.arrange(start, end, step)` : 파이썬의 `range` 와 알고리즘이 똑같으며 값의 시작, 끝, 스텝을 지정할 수 있습니다. 

* `np.linspace(start, end, bins)` : 값의 시작, 끝, 그리고 이 사이를 몇개로 나눌 것인지 정합니다. 

* `np.logspace(start, end, bins)` : `np.linspace()`와 논리가 같으나 이를 로그 스케일로 생성합니다. 


```
np.arange(0,100,10)
```





In [ ]:
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

위와 똑같은 결과를 `linspace`를 이용해 얻기 위해서는 처음값 위 배열의 처음 값 `0`, 끝값`90`, 배열의 총 길이 `10`을 적어줘야 합니다.  

```
np.linspace(0,90,10)
```

In [ ]:
np.linspace(0,90,10)

array([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])


#### **| 형태 복사하기**


이미 생성되어 있는 배열과 똑같은 `shape`를 쉽게 만들기 위해서는 `_like` 함수를 사용합니다.

* `np.empty_like(a)` :배열 `a`와 같은 형태를 가진 빈 배열을 생성합니다. 
* `np.zeros_like(a)` : 배열 `a`와 같은 형태를 가지고 모든 값이 `0`인 배열을 생성합니다.  
* `np.ones_like(a)` : 배열 `a`와 같은 형태를 가지고 모든 값이 `1`인 배열을 생성합니다.  
* `np.full_like(a, n)` : 배열 `a`와 같은 형태를 가지고 모든 값이 `n`인 배열을 생성합니다.  



배열 `a`가 다음과 같이 정의 되어 있고 앞서 배운 `ones`를 이용해 `a`와 형태가 같지만 값이 모두 `1`인 배열 `b`를 만들어 봅시다. 

```
a = np.array([1,2,3,4,5,6])
b = np.ones(6)
print(b)
```


In [ ]:
a = np.array([1,2,3,4,5,6])
b = np.ones(6)
print(b)

[1. 1. 1. 1. 1. 1.]


이를 `np.oens_like`를 이용하면 아래와 같이 작성하면 됩니다.

보통 모방하는 배열 `a`의 정확한 형태를 모르거나, `a` 가 변수처럼 상황마다 달라 정확한 `shape`를 얻기 힘들때 유용하게 사용됩니다.

```
b = np.ones_like(a)
b
```

In [ ]:
a = np.array([1,2,3,4,5,6])
b = np.ones_like(a)
print(b)

[1 1 1 1 1 1]


---
### **(3) 랜덤 배열 생성**
---


| 함수 | 설명 |
|--|--|
| `seed` | 난수 발생시 시드 지정|
| `permutation` | 임의의 순열 반환|
| `shuffle` | 배열의 순서 섞기 |
| `randint` | 특정 범위의 표본(정수) 추출 |
| `random` | 균등분포를 따르는 0~1 사이 표본 추출|
| `rand` | 균등분포를 따르는 0~1 사이 표본 추출|
| `randn` | 표준정규분포를 따르는 표본 추출 |
| `normal` | 정규분포를 따르는 표본 추출 |
| `beta` | 베타분포를 따르는 표본 추출 |
| `chisquare` | 카이제곱분포를 따르는 표본 추출 |
| `gamma` | 감마분포를 따르는 표본 추출 |

파이썬 라이브러리 `random`과 비슷하게 넘파이에도 랜덤값을 얻는 다양한 함수를 제공합니다. 

각종 분포에 대한 자세한 설명은 이후 데이터분석 수업에서 알아보도록 하고, 지금은 다양한 분포에 대한 표본을 넘파이를 통해 추출할 수 있다는 것만 알고 계시면 됩니다.

이번 시간에는 간단한 함수 몇가지만 사용해 보도록 하겠습니다.

* `np.random.randint(i1,i2, shape)` `i1` 이상 `i2` 미만 랜덤값을 지니는 `shape` 형태의 배열을 생성합니다.

```
np.random.randint(0,10, (2,3))
```


In [ ]:
import numpy as np
np.random.randint(0,10, (3,3)) # 이 함수의 경우에도 end값은 포함하지 않는다. 
np.random.randint(2,10,(5)) # 수 하나만 뽑을 것 아니면 starting point 적어야한다. 

array([7, 9, 3, 2, 5])

* `np.random.seed(n)` : 랜덤값 생성 규칙을 정합니다. (`n`은 자연수)정합니다. 


같은 `seed`에서 코드를 실행하면 똑같은 랜덤 값이 나오게 됩니다. 주로 코드를 실행하여 결과를 재현할 수 있도록 하기 위해 사용됩니다. 

```
np.random.seed(42)
np.random.randint(0,10, (2,3))
```

In [ ]:
np.random.seed(42)
np.random.randint(0,10, (2,3))

array([[6, 3, 7],
       [4, 6, 9]])

In [ ]:
np.random.randint(0,10, (2,3))

array([[2, 6, 7],
       [4, 3, 7]])

In [ ]:
np.random.seed(42)
np.random.randint(0,10, (2,3))

array([[6, 3, 7],
       [4, 6, 9]])

#### **| 균등 분포**

균등 분포란 모든 곳에서의 확률이 일정한 분포를 말합니다. 

<p align='center'>
<img src=https://github.com/yebiny/SkillTreePython-DataAnalysis/blob/main/imgs/ch0102-05.PNG?raw=trueA width=300>
</p>


* `np.random.random((shape))` : `0~1` 사이 균등분포를 가지는  `shape` 형태의 배열을 생성합니다.

* `np.random.rand(shape)` : `0~1` 사이 균등분포를 가지는  `shape` 형태의 배열을 생성합니다.


```
print(np.random.random((3,2)))
print(np.random.rand(3,2))
```
`random.random`과 `random.rand` 둘다 똑같이 균등분포를 가지는 랜덤값을 출력합니다. 차이점은 `shape`를 `random.random`은 괄호 안에 넣어주어야 한다는 것입니다.

In [ ]:
print(np.random.random((3,2)))
print(np.random.rand(3,2))

[[0.15599452 0.05808361]
 [0.86617615 0.60111501]
 [0.70807258 0.02058449]]
[[0.96990985 0.83244264]
 [0.21233911 0.18182497]
 [0.18340451 0.30424224]]


#### **| 표준정규분포**

표준정규분포는 평균이 `0`이고 편차가 `1`인 가우스(정규) 분포를 뜻합니다. 

<p align='center'>
<img src=https://github.com/yebiny/SkillTreePython-DataAnalysis/blob/main/imgs/ch0102-06.PNG?raw=trueA width=300>
</p>

* `np.random.randn(shape)` : 표준정규분포를 따르는 `shape` 형태의 배열을 생성합니다.


```
np.random.randn(3,2)
```


In [ ]:
np.random.randn(3,2)

array([[-2.61254901,  0.95036968],
       [ 0.81644508, -1.523876  ],
       [-0.42804606, -0.74240684]])

---
### **(4) 데이터 타입**
---

배열을 만들 때 어떤 값으로 채워져 있는지 이해해야 합니다. 

아래와 같이 배열 `a`,`b`,`c`를 생성합니다.

```
a = np.array([1,2,3,4])
b = np.zeros(4)
c = np.zeros_like(a)
print(a)
print(b)
print(c)
```

In [ ]:
a = np.array([1,2,3,4])
b = np.zeros(4)
c = np.zeros_like(a)
print(a)
print(b)
print(c)

[1 2 3 4]
[0. 0. 0. 0.]
[0 0 0 0]


`b`와 `c`는 `0`으로만 이루어져 있고 형태도 똑같습니다. 하지만 각 요소들은 다른 데이터 타입을 가지고 있습니다. 확인해 봅시다.

```
[type(x) for x in b], [type(x) for x in c]
```

In [ ]:
[type(x) for x in b], [type(x) for x in c]

([numpy.float64, numpy.float64, numpy.float64, numpy.float64],
 [numpy.int64, numpy.int64, numpy.int64, numpy.int64])

#### **| 여러가지 타입**

| 함수 | 설명 |
|--|--|
| `bool_` | 불리언(Boolean)|
| `int8(,16,32,64)` | 정수(-128 ~ 127)|
| `uint8(,16,32,64)` | 부호없는 정수 (0~ 255) |
| `int_` | =`int64`|
| `float16(,32,64)` | 소수점|
| `float_` | =`float64` |
| `complex64(,128)` | 복소수|
| `complex_` | =`complex128` |



* `np.---(dtype=type)` : 배열 생성시 `type`을 지정해 줍니다.

배열 `b`를 생성할 때 `int8` 타입으로 생성해 봅시다.

```
b = np.zeros(4, dtype='int8')
b, [type(x) for x in b]
```


In [ ]:
b = np.zeros(4, dtype = 'int8')
[type(x) for x in b]


[0 0 0 0]


### **(5) 배열 입출력**



#### **| 저장**

* `np.save(save_path, a)` : 배열 `a` 한개를 경로 `save_path`에 저장합니다. 

```
np.save('test1', a)
```

In [ ]:
np.save('test1', a) #현재 폴더와 같은 경로에 test1.npy 로 저장이 되었다. 

* `np.savez(save_path, a1, a2, ...)` : 배열  여러개를 경로 `save_path`에 저장합니다. 

```
np.savez('test2', a, a)
```

In [2]:
a = [1,2,3]
b = [4,5,6]
np.savez('test2',a,b)

저장 시 각 배열에 대한 이름을 지정해 줄수 있습니다.
```
np.savez('test3', a1=a, a2=a)
```

In [ ]:
np.savez('test3', a = a, b = b)

#### **| 불러오기**

* `np.load(file_path)` : 넘파이 배열이 저장된 파일로부터 객체를 불러옵니다. 


```
a_npy = np.load('test.npy')
```

In [ ]:
a_npy = np.load('test1.npy')
a_npy

array([1, 2, 3, 4])

배열이 여러개 들어간 `npz` 파일을 불러올 때는 어떤 이름으로 각 배열이 저장되어 있는지 확인해 볼 필요가 있습니다.

```
a_npz = np.load('test3.npz')
for a in a_npz:
  print(a)
```

In [3]:
import numpy as np
a_npz = np.load('test2.npz')
for a in a_npz:
    print(a)

arr_0
arr_1


이름 확인 후 인덱싱을 통해 각 배열에 접근 할 수 있습니다.

```
print(a_npz['a1'], a_npz['a2'])
```

In [ ]:
print(a_npz['a'], a_npz['b'])
a = a_npz['a']
a

[1 2 3 4] [0 0 0 0]


array([1, 2, 3, 4])

## 문제풀이
---


**예제 01**

아래그림과 같이 `shape`가 `(4)` 인 배열을 생성하고 `a1`로 바인딩 하세요.

<p align='center'>
<img src=https://github.com/yebiny/SkillTreePython-DataAnalysis/blob/main/imgs/ch0102-07.png?raw=trueA width=180>
</p>

In [12]:
a1 = np.array([2,4,1,3])
a1, a1.shape

(array([2, 4, 1, 3]), (4,))

**예제 02**

`a1`와 `shape`가 똑같고 모든 값이 `1`인 배열을 생성하세요.

In [ ]:
a1_like = np.ones_like(a1)
a1_like, a1_like.shape

(array([1, 1, 1, 1]), (4,))

**예제 03**

`a1`와 모든 값이 같지만 `shape`가 `(1,4)`인 배열을 생성하세요.

In [16]:
a1_copy = np.array([a1])
a1_copy, a1_copy.shape

(array([[2, 4, 1, 3]]), (1, 4))

**예제 04**

아래그림과 같이 `shape`가 `(4,2)`인 배열을 생성하고 `a2`로 바인딩 하세요.


<p align='center'>
<img src=https://github.com/yebiny/SkillTreePython-DataAnalysis/blob/main/imgs/ch0102-08.png?raw=trueA width=80>
</p>


In [18]:
a2 = np.array([
            [1,0],
            [1,0],
            [3,2],
            [1,1]
            ])
a2, a2.shape

(array([[1, 0],
        [1, 0],
        [3, 2],
        [1, 1]]), (4, 2))

**예제 05**

`a2`와 `shape`가 똑같고 모든 값이 `0`인 배열을 생성하세요.

In [ ]:
a2_zeros = np.zeros_like(a2)
a2_zeros, a2_zeros.shape  

(array([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]]), (4, 2))

**예제 06**

`a2`와 모든 값이 같지만 `shape`가 `(4,1,2)`인 배열을 생성하세요.

In [21]:
a2to3 = np.array([
                 [[1,0]],
                 [[1,0]],
                 [[3,2]],
                 [[1,1]]
                ])
a2to3, a2to3.shape


(array([[[1, 0]],
 
        [[1, 0]],
 
        [[3, 2]],
 
        [[1, 1]]]), (4, 1, 2))

**예제 07**

`a2`와 모든 값이 같지만 아래와 같이 전치된 배열을 생성하세요.


<p align='center'>
<img src=https://github.com/yebiny/SkillTreePython-DataAnalysis/blob/main/imgs/ch0102-09.png?raw=trueA width=180>
</p>

In [24]:
# a.T 
# np.transpose(a) method / a.transpose()
# np.swapaxes(a, 0, 1) method / a.swapaxes(0,1)

a2_T =a2.T
print(a2_T, a2_T.shape)
a2_TT = np.transpose(a2)
print(a2_TT, a2_TT.shape)

[[1 1 3 1]
 [0 0 2 1]] (2, 4)
[[1 1 3 1]
 [0 0 2 1]] (2, 4)


**예제 08**

모든 값이 `3`이고 `shape`가 `(5,1,2)`인 3차원 배열을 생성 후 `shape`를 확인하세요.

In [ ]:
threes = np.full((5,1,2), 3)
threes, threes.shape

(array([[[3, 3]],
 
        [[3, 3]],
 
        [[3, 3]],
 
        [[3, 3]],
 
        [[3, 3]]]), (5, 1, 2))

**예제 09**

모든 값이 `3`이고 `shape`가 `(1,2,5)`인 3차원 배열을 생성 후 `shape`를 확인하세요.

In [ ]:
threes = np.full((1,2,5),3)
threes, threes.shape

(array([[[3, 3, 3, 3, 3],
         [3, 3, 3, 3, 3]]]), (1, 2, 5))

**예제 10**

모든 값이 3이고 shape가 `(2,1,3)`인 3차원 배열을 리스트를 이용해 직접 만들고 `shape`를 확인하세요.

In [ ]:
threes_hand = np.array([
                        [[3,3,3]],
                        [[3,3,3]]
                        ])
threes_hand, threes_hand.shape

(array([[[3, 3, 3]],
 
        [[3, 3, 3]]]), (2, 1, 3))

**예제 11**

1에서 100까지 홀수값만을 가지는 배열을 `np.arange`를 이용해 생성하세요.


In [ ]:
odd = np.arange(1,100,2)
odd, odd.shape

(array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
        35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
        69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]),
 (50,))

**예제 12**

1에서 100까지 홀수값만을 가지는 배열을 `np.linspace`를 이용해 생성하세요.

In [ ]:
odd = np.linspace(1,99,50, dtype = 'int8')
odd, odd.shape

(array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
        35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
        69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99],
       dtype=int8), (50,))

**예제 13**

`shape`가 `(5,5)`인 단위행렬(Identity matrix)를 생성하세요.


In [ ]:
eye = np.eye(5)
eye, eye.shape

(array([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]), (5, 5))

**예제 14**

`shape`가 `(10,5)`이고 균등분포를 따르는 배열을 생성하세요. 랜덤시드를 `42`로 정해주세요.


In [ ]:
np.random.seed(42)
np_seed = np.random.random((10,5))
print(np_seed, np_seed.shape)


[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
 [0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184 0.45606998]
 [0.78517596 0.19967378 0.51423444 0.59241457 0.04645041]
 [0.60754485 0.17052412 0.06505159 0.94888554 0.96563203]
 [0.80839735 0.30461377 0.09767211 0.68423303 0.44015249]
 [0.12203823 0.49517691 0.03438852 0.9093204  0.25877998]
 [0.66252228 0.31171108 0.52006802 0.54671028 0.18485446]] (10, 5)


**예제 15**

`shape`가 `(10,5)`이고 표준정규분포를 따르는 배열을 생성하세요. 랜덤시드를 `42`로 정해주세요.


In [ ]:
np.random.seed(42)
rand_n = np.random.randn(10,5)
print(rand_n, rand_n.shape)


[[ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337]
 [-0.23413696  1.57921282  0.76743473 -0.46947439  0.54256004]
 [-0.46341769 -0.46572975  0.24196227 -1.91328024 -1.72491783]
 [-0.56228753 -1.01283112  0.31424733 -0.90802408 -1.4123037 ]
 [ 1.46564877 -0.2257763   0.0675282  -1.42474819 -0.54438272]
 [ 0.11092259 -1.15099358  0.37569802 -0.60063869 -0.29169375]
 [-0.60170661  1.85227818 -0.01349722 -1.05771093  0.82254491]
 [-1.22084365  0.2088636  -1.95967012 -1.32818605  0.19686124]
 [ 0.73846658  0.17136828 -0.11564828 -0.3011037  -1.47852199]
 [-0.71984421 -0.46063877  1.05712223  0.34361829 -1.76304016]] (10, 5)


**예제 16**

`a1`의 `shape`와 데이터 `type`을 확인하세요. 모든 값을 `int64`로 변경하고 타입을 확인하세요.

In [ ]:
print(a1.shape, [type(x) for x in a1])

(4,) [<class 'numpy.int64'>, <class 'numpy.int64'>, <class 'numpy.int64'>, <class 'numpy.int64'>]


**예제 17**

`a2`의 `shape`와 데이터 `type`을 확인하세요. 모든 값을 `float64`로 변경하고 타입을 확인하세요.

In [39]:
print(a2.shape, [type(j) for i in a2 for j in i])

(4, 2) [<class 'numpy.int64'>, <class 'numpy.int64'>, <class 'numpy.int64'>, <class 'numpy.int64'>, <class 'numpy.int64'>, <class 'numpy.int64'>, <class 'numpy.int64'>, <class 'numpy.int64'>]


In [41]:
a2 = np.array(a2, dtype = 'float64')
print(a2.shape, [type(j) for i in a2 for j in i])

(4, 2) [<class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>]


**예제 18**

`a1`을 `.npy`파일로 저장하세요. 경로는 `02_quest18.npy` 입니다.

In [ ]:
np.save('02_quest18.npy', a1)

**예제 18**

`a1`과 `a2`를 `npz`파일로 저장하세요. 경로는 `02_quest19.npz` 입니다.

In [44]:
np.savez('02_quest19', a1, a2)

**예제 20**

위에서 저장한 파일을 모두 불러오고 저장된 배열들을 출력하세요.

In [45]:
np.load('02_quest18.npy')

array([2, 4, 1, 3])

In [48]:
load = np.load('02_quest19.npz')
for ar in load:
    print(ar)
print(load['arr_0'],load['arr_1'] )

arr_0
arr_1
[2 4 1 3] [[1. 0.]
 [1. 0.]
 [3. 2.]
 [1. 1.]]


**예제 21**

`ch02_quest18.npy`와 `ch02_quest19.npy` 를 깃허브 `results`폴더에 추가해 주세요.

In [ ]:
# 선생님께서 만들어둔 results폴더에 있습니다.